### ISSUE TITLE
How to construct the graph

### ISSUE THREAD

**Issue by MrFisher97** [PIX2NVS/NVS_FeatureLearning#1]
From your paper "Graph-Based Spatio-Temporal Feature Learning for Neuromorphic Vision Sensing", I learned that you used the non-uniform grid sampling, but you didn't provide the code to sample and generate the graph from the dataset. Is it possible to public your code about how to generate the graph from the raw dataset?

**Comment by wangxiao5791509** [comment]
@wanzengy  same problem ...
