### ISSUE TITLE
Train/test splits

### ISSUE THREAD

**Issue by AlbertoSabater** [PIX2NVS/NVS_FeatureLearning#2]
Hi! I would like to know how you have made the train/test splits for the HMDB and UCF datasets.
Thanks in advance

**Comment by PIX2NVS** [comment]
Hi, thanks for the interests. Please refer to original RGB video datasets for the information how to split the train/test sets. 
e.g., for UCF101:  https://www.crcv.ucf.edu/data/UCF101.php
